project_id = "epcelmrwfqniycdrxaoi"

[functions.auto-login]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.check-user-exists]
verify_jwt = false


[functions.notify-new-request]
verify_jwt = false

[functions.retry-failed-notifications]
verify_jwt = false
